models.py
from . import db, login_manager
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    first_name = db.Column(db.String(255), index = True)
    last_name = db.Column(db.String(255), index = True)
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255), unique = True, index = True)
    password_hash = db.Column(db.String(255))   
    pitches =  db.relationship('Pitch', backref = 'user', lazy = "dynamic")
    reviews = db.relationship('Review', backref = 'user', lazy = "dynamic")
    role = db.relationship('Role',backref='user' ,lazy="dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    # def __repr__(self):
    #     return f'User {self.username}'


class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255), index = True)
    post = db.Column(db.String(300), index = True)
    time = db.Column(db.DateTime, default = datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    category = db.Column(db.String(255), index = True)
    upvote = db.Column(db.Integer)
    downvote = db.Column(db.Integer)
    reviews = db.relationship('Review', backref = 'pitch', lazy = "dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls, id):
        pitches = Pitch.query.filter_by(category_id = id).all()
        return pitches

class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    # def __repr__(self):
    #     return f'User {self.name}'


class Review(db.Model):
    __tablename__ = 'reviews'

    id = db.Column(db.Integer, primary_key = True)
    post_review = db.Column(db.String(255), index = True)
    time = db.Column(db.DateTime, default = datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))
    posted_by= db.Column(db.String)

    def save_review(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_reviews(cls, id):
        reviews = Review.query.filter_by(pitch_id=id).all()
        return reviews
    

main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required 

class ReviewForm(FlaskForm):
    title = StringField('Comment')
    comment = TextAreaField('Enter your comment')
    submit = SubmitField('submit')
    
class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')
class PitchForm(FlaskForm):
    title = StringField('Pitch Title', validators=[Required()])
    pitch = TextAreaField('Your Pitch', validators=[Required()])
    category = SelectField('Category', choices=[('Production','Production'),('Movie','Movie'),('Job','Job'),('Promotion','Promotion'),('Sales','Sales'),('Advertisement','Advertisement')],validators=[Required()])
    submit = SubmitField('Type / Copy and Paste Your Pitch Here')

__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()

def create_app(config_name):
    
    app = Flask(__name__)
    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')
    
    
    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    
    return app

main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error
# from flask_uploads import UploadSet,configure_uploads,IMAGES


# photos = UploadSet('photos',IMAGES)
# def create_app(config_name):
#     app = Flask(__name__)
#     # configure UploadSet
#     configure_uploads(app,photos)

#     # Creating the app configurations
#     app.config.from_object(config_options[config_name])

#     # Initializing flask extensions
#     bootstrap.init_app(app)
    
#     # Registering the blueprint
#     from .main import main as main_blueprint
#     app.register_blueprint(main_blueprint)

#     return app  

main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import ReviewForm,UpdateProfile,PitchForm
from ..models import Review,User,Pitch
from flask_login import login_required,current_user
from .. import db,photos
import markdown2  

@main.route('/')
def index():
    '''
    view root page function that returns index page
    '''
    # category = Category.get_categories()

    title = 'Home'
    return render_template('index.html', title = title)


@main.route('/pitches',methods = ['GET','POST'])
@login_required
def new_pitch():
    name = "Pitch"
    title = 'Welcome,Pitch your one-minute pitch!'
    form = PitchForm()
    
    if form.validate_on_submit():
        
        title=form.title.data
        post=form.pitch.data
        # upvote=0
        # downvote=0
        new_pitch = Pitch(title=title, post=post)
        
        db.session.add(new_pitch)
        db.session.commit()
        
        
        # new_pitch.save_pitch()
        return redirect(url_for('main.post_pitch'))


    return render_template('post.html',title = title, name=name, pitch_form =form)


@main.route('/posts')
@login_required
def post_pitch():
    pitches = Pitch.query.all()
    return render_template('new_pitch.html',pitches = pitches)


@main.route('/reviews/<id>',methods = ['GET', 'POST'])
def post_review(id):
    pitch = Pitch.query.filter_by(id=id).first()
    form = ReviewForm()
    
    if form.validate_on_submit():
        title = form.title.data
        review = form.review.data
        
        new_review = Review(review_title = title, review = review, pitch_id=id, posted_by=current_user.username)
        new_review.save_review()
        return redirect(url_for('.post_review',id=pitch.id))
    return render_template('reviews.html',form=form, pitch=pitch)



@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
            abort(404)
    form = UpdateProfile()

    if form.validate_on_submit():

        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)



@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = 'photos/{}'.format(filename)
        print(path)
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

    
    
    
    
    
    

templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block  -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %} {%block styles %} {{super()}}
<!--Importing the simple mde css and js files  -->
{{ simplemde.css}} {{ simplemde.js }} {% endblock %}

templates/index.html
{% extends 'base.html' %} {% import 'macros.html' as macro %}

<!-- styles block -->
{% block styles %} {{ super() }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='/css/style.css') }}"> {% endblock %}

<!-- content block -->
{% block content %}

<body background="{{ url_for('static', filename='photos/background.jpg') }}">

    <div class="container" id="index-container">
        <div class="row ">

            <h1 style="color:crimson height:30px; font; outline font-size:80px;" class="text-center"><em>One Minute Pitch</em></h1>
            <h2 style="font-style:italic;font-size: 30px;color: green;" class="text-center"> Hi Adorable You have 60 seconds to creat your pitch. </h2>
            <div class="col-md-3">

            </div>

            <div class="col-md-6 text-center">
                <a href="{{url_for('main.new_pitch')}}" class="btn btn-primary">Click To Add Pitch</a>
                <a href="{{url_for('main.post_pitch')}}" class="btn btn-primary">View Your Pitch</a>
            </div>

            <div class="col-md-3">
</body>
</div>

</div>
</div>
{% endblock %}

templates/macros.html
{% macro displayCategories(category_list) %} {% for category in category_list %}
<li id="categories">
    <a class="category-button btn btn-default" href="/category/{{category.id}}">
        <h3>{{category.name}}</h3>
    </a>
</li>
{% endfor %} {% endmacro %} % macro displayPitches(pitch_list) %} {% for pitch in pitch_list %}
<div class="well col-xs-12 col-sm-4 col-md-4 col-lg-4 pitch-card">
    <div class="row avatar-row">
        <div class="col-md-2 col-lg-2" id="avatar-column">
            <img id="avatar" src="/static/img/avatar.png" alt="Avatar">
        </div>
        <div class="col-md-8 col-lg-8">
            <h4>{{pitch.user.username}}</h4>
            <p>Posted on {{pitch.time}}</p>
        </div>
    </div>
    <hr>
    <div class="row pitch-content">
        <h4><b>{{pitch.title}}</b></h4>
        <p>{{pitch.post}}</p>
    </div>
    <a href="/pitch/reviews/{{pitch.id}}">View Reviews</a>
</div>
{% endfor %} {% macro displayReviews(review_list) %} {% for review in review_list %}
<div class="well reviews-well">
    <li>
        <h3>{{review.post_review}}</h3>
        <p>by {{review.user.username}}</p>
    </li>
</div>
{% endfor %} {% endmacro %}

templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="navbar-header">
        <a style="color: blue; align-content: center height:15px;" class="navbar-brand" href="/"> One Minute Pitch</a>

    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li><a href="/">Nyumbani</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li style="color:white;padding:9px;">{{current_user.username}}</li>
            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.register')}}">Register.</a></li>
            <li class="divider"></li>
            <li><a href="{{url_for('auth.login')}}">Siign in</a></li>
            {% endif %}
        </ul>
    </div>
</div>

templates/new  _review.html
{% extends 'base.html' %} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<div class="container">
    <div class="panel form-panel">
        {{ wtf.quick_form(review_form) }}
    </div>
</div>
{% endblock %}

templates/new_pitch.html
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %} {% block content %}{%for pitches in pitches%}
<table class="table col-md 12">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Pitch Title</th>
            <th scope="col">Pitch Post</th>
            <th scope="col">Pitch category</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">{{pitches.id}}</th>
            <td>{{pitches.title}}</td>
            <td>{{pitches.post}}</td>
            <td>{{pitches.category}}</td>
        </tr>
    </tbody>
</table>
{%endfor%} {% endblock %}

templates/new_review.html
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %} {% block content %}{%for pitches in pitches%}
<table class="table col-md 12">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Pitch Title</th>
            <th scope="col">Pitch Post</th>
            <th scope="col">Pitch category</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">{{pitches.id}}</th>
            <td>{{pitches.title}}</td>
            <td>{{pitches.post}}</td>
            <td>{{pitches.category}}</td>
        </tr>
    </tbody>
</table>
{%endfor%} {% endblock %}

templates/post.html
{% extends 'base.html' %} {% import "bootstrap/wtf.html" as wtf %} {% block content %}

<div class="container">
    <div class="panel form-panel">
        {{ wtf.quick_form(pitch_form) }}
    </div>
</div>

{% endblock %}

templates/profile/profile.html
{% extends 'base.html'%} {% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">
            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail"> {%else%}
            <p>No profile to display </p>

            {% endif %} {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/profile/update.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% if user == current_user %}
<a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a> {% endif %} {% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

templates/reviews.html
% extends 'base.html' %} {% import 'macros.html' as macro %} {% block content %}
<div class="container">
    <div class="panel reviews">
        <a href="/pitch/review/new/{{pitch.id}}">
            <h3>Create a Review</h3>
        </a>
        {% if review %}
        <ul class="reviews-list">
            {{ macro.displayReviews(review) }}
        </ul>
        {% else %}
        <h3>This pitch has no reviews</h3>
        {% endif %}
    </div>
</div>
{% endblock %}